* Rahil Sayyad
* Email id: rahilsayyad389@gmail.com

In [1]:
import numpy as np

In [2]:
Rs=[1,2,3,4,5,6]

In [3]:
Rs

[1, 2, 3, 4, 5, 6]

In [4]:
Sr=np.array(Rs)

In [5]:
Sr

array([1, 2, 3, 4, 5, 6])

## access a array item using index number

In [8]:
Sr[0]

1

In [9]:
Sr[1:]

array([2, 3, 4, 5, 6])

In [11]:
Sr[-3:-1]

array([4, 5])

In [13]:
np.shape(Sr)

(6,)

In [15]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]]) # create 2d array

In [16]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
a[1:,1:3] # access a item using index (row, column)

array([[4, 5],
       [7, 8]])

In [19]:
a[1:3,0:1]

array([[3],
       [6]])

In [20]:
a[0]

array([1, 2, 3])

In [24]:
a[1,1]

4

In [25]:
b=np.arange(20) # create array in specific range
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
c=np.arange(4,20)

In [27]:
c

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
d=np.arange(3,20,2)

In [29]:
d

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
b.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.zeros((2,3))#create zeros number of array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.linspace(2,10,5)# linespace is used to create eual no of array

array([ 2.,  4.,  6.,  8., 10.])

In [37]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [38]:
np.identity(3) # create indentity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
x=np.random.rand(10) # create a uniform distribution random no of array

In [40]:
x

array([0.0147006 , 0.37867747, 0.20657916, 0.10956546, 0.51728696,
       0.97242735, 0.22458182, 0.92534584, 0.34451196, 0.63781692])

In [41]:
np.random.rand(2,10)

array([[0.95412144, 0.00989351, 0.83918119, 0.64800524, 0.96340097,
        0.83095145, 0.7336203 , 0.98654991, 0.58151025, 0.87034131],
       [0.25595129, 0.46093882, 0.01302653, 0.14767632, 0.55283638,
        0.9020085 , 0.11710301, 0.46641658, 0.04362288, 0.97105117]])

In [42]:
np.random.rand(2,5,3)

array([[[0.02994143, 0.90881134, 0.70890042],
        [0.09829782, 0.12141572, 0.99598223],
        [0.34254279, 0.89481342, 0.71108208],
        [0.59321856, 0.34381784, 0.64781477],
        [0.33756009, 0.62419844, 0.15568541]],

       [[0.60939029, 0.28383152, 0.60881273],
        [0.25275192, 0.38083572, 0.19884404],
        [0.32663151, 0.21221261, 0.10681351],
        [0.13421971, 0.76668939, 0.30681355],
        [0.53579726, 0.03559339, 0.6038281 ]]])

In [43]:
np.random.randn(20) # create a standard distribution random no of array

array([-0.60646752,  0.74536522, -1.31303468,  0.01215623,  0.27222538,
       -0.43176381,  0.27751181,  1.09964561, -0.08540097,  0.32984424,
        0.51305147, -0.56796344,  0.75716521,  0.20501633,  0.81069942,
        0.03579167,  1.16986674, -0.70400728, -0.74626115, -1.17700914])

In [46]:
np.random.randn(3,4)

array([[ 1.82568592, -0.56815818,  0.00743275,  0.55278325],
       [ 1.09541659, -0.95222708,  1.11516481,  0.30855915],
       [ 0.66901834, -0.34725425,  1.20181896, -1.06911044]])

In [48]:
np.random.randn(3,4,2)

array([[[-0.1712563 , -0.79710005],
        [ 0.6345677 ,  1.71135913],
        [-1.76731286, -0.16117617],
        [-0.00795992, -0.73648775]],

       [[-0.11251892,  0.25504597],
        [ 0.20715869, -2.13732172],
        [-1.41802736,  0.38071594],
        [ 0.81928915,  0.2169411 ]],

       [[ 0.70209005, -1.15648278],
        [ 1.03409762, -1.15897749],
        [ 1.7909548 , -0.23305412],
        [ 1.33552535,  1.34577556]]])

In [4]:
np.random.randint(29) # create a int random no of array

7

In [52]:
np.random.randint(5,10)

7

In [54]:
y=np.random.randint(5,10,20)

In [55]:
y

array([9, 6, 8, 5, 7, 8, 7, 7, 8, 9, 7, 6, 6, 7, 6, 7, 7, 8, 7, 5])

In [56]:
y.reshape(5,4)

array([[9, 6, 8, 5],
       [7, 8, 7, 7],
       [8, 9, 7, 6],
       [6, 7, 6, 7],
       [7, 8, 7, 5]])

## agrigate function

In [57]:
y.max()

9

In [58]:
y.min()

5

In [59]:
y.argmax()

0

In [60]:
y.argmin()

3

In [61]:
y.sum()

140

In [63]:
z=np.arange(20)

## conditional selection

In [64]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
r=z>16

In [68]:
r

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True])

In [70]:
z[r]

array([17, 18, 19])

In [66]:
z[z>16]

array([17, 18, 19])

In [71]:
m=13
z[z>m]

array([14, 15, 16, 17, 18, 19])

In [8]:
L1=[["rahil","sohel","sarthak"],["rutik","raj","sim"]]

In [9]:
L1


[['rahil', 'sohel', 'sarthak'], ['rutik', 'raj', 'sim']]

In [10]:
Rs=np.array(L1)

In [11]:
Rs

array([['rahil', 'sohel', 'sarthak'],
       ['rutik', 'raj', 'sim']], dtype='<U7')

In [12]:
Rs[0,0]

'rahil'

In [13]:
Rs[0,1]

'sohel'

In [14]:
Rs[0:,0:2]

array([['rahil', 'sohel'],
       ['rutik', 'raj']], dtype='<U7')

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(9,12)

array([ 9, 10, 11])

In [17]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [18]:
np.random.rand(13)

array([0.54760995, 0.31387752, 0.0561153 , 0.37743675, 0.45025026,
       0.62441761, 0.6727553 , 0.58365733, 0.52171696, 0.98166098,
       0.19010695, 0.7508978 , 0.96941694])

In [19]:
np.random.rand(2,13)

array([[0.79811253, 0.66867195, 0.17134296, 0.93834461, 0.95494563,
        0.26495172, 0.55224393, 0.08371321, 0.14806297, 0.35682403,
        0.2159096 , 0.29453006, 0.48446207],
       [0.25548501, 0.36866814, 0.96213755, 0.47913925, 0.62399211,
        0.87821223, 0.96111186, 0.55149712, 0.25631898, 0.08332308,
        0.89270075, 0.6119881 , 0.47336936]])

In [20]:
np.random.rand(2,13,3)

array([[[0.22679782, 0.76499007, 0.39958476],
        [0.8526897 , 0.26151338, 0.40388493],
        [0.83303103, 0.32868304, 0.66594192],
        [0.74224979, 0.74430894, 0.48595369],
        [0.88159114, 0.19885658, 0.26344815],
        [0.47209051, 0.50845124, 0.59201273],
        [0.57083397, 0.47622894, 0.28222759],
        [0.61214616, 0.68792568, 0.11909836],
        [0.39858819, 0.36653874, 0.57365292],
        [0.39775819, 0.07705543, 0.80381715],
        [0.79161546, 0.68674521, 0.39842074],
        [0.88497669, 0.36119146, 0.21030649],
        [0.56132321, 0.30469122, 0.37610825]],

       [[0.99869573, 0.45386667, 0.04810167],
        [0.27165891, 0.30618484, 0.31067295],
        [0.2490511 , 0.80365911, 0.1863391 ],
        [0.25383167, 0.49292786, 0.03811992],
        [0.88091219, 0.17917897, 0.65963298],
        [0.37505681, 0.14524537, 0.54386801],
        [0.23141733, 0.78456809, 0.05852261],
        [0.45243052, 0.79995082, 0.8424961 ],
        [0.36345983, 0.24001759,

In [22]:
np.random.randn(15)

array([-0.43835222,  0.48186368, -0.1071836 , -0.51419829, -0.5557761 ,
        0.19332425,  1.07094958,  0.3265322 , -2.34620574,  0.04045535,
       -0.33580215, -1.08367518,  0.50238581,  0.11303606,  0.39428094])

In [23]:
np.random.rand(2,13)

array([[0.61686767, 0.4325696 , 0.32559606, 0.96309233, 0.05509306,
        0.3978035 , 0.37661386, 0.69387106, 0.51438835, 0.23212905,
        0.831119  , 0.86904137, 0.57900854],
       [0.32261601, 0.56229076, 0.65693484, 0.88850344, 0.0931242 ,
        0.52451913, 0.55851676, 0.30202101, 0.39550689, 0.22342949,
        0.08206264, 0.52886631, 0.02818626]])

In [24]:
np.random.rand(3,14,4)

array([[[0.13947365, 0.4870379 , 0.91748639, 0.12123581],
        [0.8818847 , 0.73923787, 0.08370519, 0.98873458],
        [0.65243829, 0.10215973, 0.55993007, 0.13813027],
        [0.95613816, 0.69711119, 0.63615299, 0.25353876],
        [0.76034715, 0.85149375, 0.89390435, 0.84831848],
        [0.81880181, 0.20153573, 0.59934387, 0.47812949],
        [0.24589601, 0.77713162, 0.59660969, 0.17752679],
        [0.09531231, 0.74188846, 0.93238163, 0.30509072],
        [0.75247992, 0.41199013, 0.24014361, 0.14812467],
        [0.43911441, 0.59269422, 0.85954483, 0.78303844],
        [0.99336178, 0.32884478, 0.40218699, 0.97962039],
        [0.89724687, 0.26946401, 0.40034275, 0.88557436],
        [0.52693796, 0.70785201, 0.15381533, 0.62452201],
        [0.88301808, 0.8316397 , 0.20597998, 0.03553052]],

       [[0.83803058, 0.93974716, 0.39890121, 0.96224412],
        [0.71950415, 0.40645547, 0.17250155, 0.63506013],
        [0.43244529, 0.10672967, 0.31555569, 0.9246198 ],
        [0.0

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.zeros(4)

array([0., 0., 0., 0.])

In [28]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.linspace(2,50,6)

array([ 2. , 11.6, 21.2, 30.8, 40.4, 50. ])

In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.randint(5)

1

In [34]:
np.random.randint(2,5)

3

In [48]:
np.random.randint(0,5,6)

array([4, 2, 3, 0, 4, 3])

In [52]:
x=np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
x.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [54]:
x.max()

49

In [55]:
x.min()

0

In [56]:
x.argmax()

49

In [57]:
x[-1]

49

In [58]:
x[20]

20

In [59]:
x[0:5]

array([0, 1, 2, 3, 4])

In [60]:
x[-7:-1]

array([43, 44, 45, 46, 47, 48])

In [65]:
y=np.array([[2,3,4],[6,7,8]])

In [66]:
y

array([[2, 3, 4],
       [6, 7, 8]])

In [67]:
y[0,0]

2

In [68]:
y[1]

array([6, 7, 8])

In [69]:
y[0:2,1:]

array([[3, 4],
       [7, 8]])

In [70]:
x[x>44]

array([45, 46, 47, 48, 49])

In [71]:
x>20

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [72]:
x<49

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [73]:
i=20
x[x>i]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## arithmatic operation

In [74]:
x/x

C:\Users\Rahil\AppData\Local\Temp\ipykernel_15168\1506400357.py:1: RuntimeWarning: invalid value encountered in true_divide
  x/x


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
x+x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [76]:
x**3

array([     0,      1,      8,     27,     64,    125,    216,    343,
          512,    729,   1000,   1331,   1728,   2197,   2744,   3375,
         4096,   4913,   5832,   6859,   8000,   9261,  10648,  12167,
        13824,  15625,  17576,  19683,  21952,  24389,  27000,  29791,
        32768,  35937,  39304,  42875,  46656,  50653,  54872,  59319,
        64000,  68921,  74088,  79507,  85184,  91125,  97336, 103823,
       110592, 117649], dtype=int32)

In [77]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46])

In [78]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [79]:
np.log(x)

C:\Users\Rahil\AppData\Local\Temp\ipykernel_15168\1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ])

In [80]:
np.sin(y)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [81]:
np.min(y)

2

# format mathod {}


In [ ]:
#40<fail
#60> and <=75 pass
#75>and <=90 first class
#90> distinction

In [10]:
name=["Rahil","Yash","Raj","mayur","Suraj","Tejas"]
marks=[78,50,45,90,69,96]
grade=["Fail","Pass","First Class","Distinction"]
for i in range(0 ,len(grade)):
        if marks[i]>40:
            print("{0} got {1}% ,he is {2}".format(name[i],marks[i],grade[i]))
        elif marks[i]>60 and marks[i]<=75:
            print("{0} got {1}% ,he is {2}".format(name[i],marks[i],grade[i]))
        elif marks[i]>75 and marks[i]<=90:
            print("{0} got {1}% ,he is {2}".format(name[i],marks[i],grade[i]))
        elif marks[i]>90:
            print("{0} got {1}% ,he is {2}".format(name[i],marks[i],grade[i]))

Rahil got 78% ,he is Fail
Yash got 50% ,he is Pass
Raj got 45% ,he is First Class
mayur got 90% ,he is Distinction
