* Rahil Sayyad
* Email id: rahilsayyad389@gmail.com

## numpy

In [2]:
import numpy as np

In [3]:

RS= np.array([1,2,3,4,5])
RS

array([1, 2, 3, 4, 5])

In [4]:
RS.shape

(5,)

In [5]:
my = [[1,2,3],[4,5,6],[7,8,9]]
my

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
m=np.array(my)


In [7]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.shape(m)

(3, 3)

In [9]:
np.arange(1,10,2)# create array in specific range

array([1, 3, 5, 7, 9])

In [12]:
np.arange(0,11,3)

array([0, 3, 6, 9])

## create zeros number of array

In [13]:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## create zeros number of array

In [14]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(10,100,10) # linespace is used to create eual no of array

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.identity(4) # create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(1,5,10) # create a uniform distribution random no of array

array([[[0.71585894, 0.80532835, 0.49750152, 0.13502535, 0.07566963,
         0.5415134 , 0.27426076, 0.11928534, 0.49148643, 0.66557633],
        [0.19335419, 0.44742798, 0.96177867, 0.33283573, 0.08324379,
         0.7023419 , 0.9551631 , 0.00643921, 0.85849562, 0.28970955],
        [0.87127769, 0.01904596, 0.35780561, 0.90671322, 0.17177905,
         0.07158289, 0.5902769 , 0.08254633, 0.82958304, 0.69943951],
        [0.96662559, 0.91156722, 0.52668211, 0.63198925, 0.75733749,
         0.12367524, 0.146444  , 0.97928243, 0.14441913, 0.34110963],
        [0.47649057, 0.23505962, 0.07614282, 0.13852201, 0.41020313,
         0.50674082, 0.87068765, 0.76032454, 0.87195625, 0.95924571]]])

In [23]:
np.random.rand(2,5,2)

array([[[0.02420126, 0.23253693],
        [0.04502753, 0.19538979],
        [0.17287673, 0.84579844],
        [0.64954758, 0.95755413],
        [0.6524075 , 0.42319167]],

       [[0.37804433, 0.65553424],
        [0.61026493, 0.98014811],
        [0.27505002, 0.89185676],
        [0.20612168, 0.05168079],
        [0.88125639, 0.30573655]]])

In [26]:
np.random.randn(2)  # create a standard distribution random no of array

array([1.15313134, 1.60219946])

In [27]:
np.random.randn(5,5).shape

(5, 5)

In [28]:
np.random.randint(1,10)  # create a int random no of array

5

In [29]:
np.random.randint(2,30,3)

array([ 7, 12, 25])

In [44]:
a = np.arange(1,29)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [45]:
len(a) # find a length

28

In [46]:
a.reshape(4,7) # create a array in new shape

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [47]:
jon = np.random.randint(0,50,10)
jon

array([25, 47, 10,  3, 36,  6,  4, 49, 17, 24])

## agrigate function

In [48]:
jon.max()

49

In [49]:
jon.min()

3

In [50]:
jon.argmax()

7

In [52]:
jon.argmin()

3

In [53]:
jon.sum()

221

In [56]:
ab=np.arange(25)

In [57]:
ab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ab.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
ab.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [60]:
ab.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])