In [2]:
import numpy as np

In [3]:
x = np.arange(5,22)

x

## access a array item using index number

In [5]:
x[1]

6

In [6]:
x[-4] # access a array item using index number

18

In [13]:
x[:11]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
x[4:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [7]:
x[2:15:2]

array([ 7,  9, 11, 13, 15, 17, 19])

In [8]:
y=np.array([[1,2,3,4],[5,6,7,8]]) # create 2d array

In [9]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
y[0]

array([1, 2, 3, 4])

In [11]:
y[0,1]

2

In [12]:
y[0:,0:2]

array([[1, 2],
       [5, 6]])

## conditional selection

In [15]:
xy=np.arange(25)

In [16]:
xy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
xy[xy>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [18]:
xy[xy<21]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [19]:
nm=xy>6

In [20]:
nm

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])