* Rahil Sayyad
* Email id: rahilsayyad389@gmail.com

In [4]:
import numpy as np

In [7]:
xy=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # create 2d array
xy

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## aritmatic operation

In [8]:
xy*2

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [9]:
xy-2

array([[[-1,  0,  1],
        [ 2,  3,  4],
        [ 5,  6,  7]]])

In [10]:
xy-xy

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [11]:
xy/3

array([[[0.33333333, 0.66666667, 1.        ],
        [1.33333333, 1.66666667, 2.        ],
        [2.33333333, 2.66666667, 3.        ]]])

In [12]:
xy+xy

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [13]:
xy**2

array([[[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]], dtype=int32)

In [26]:
a=np.array([[1,2,3],[2,3,4],[4,5,1]])

In [27]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 1]])

In [28]:
b=np.array([[2,3,4],[1,2,3],[2,5,1]])
b

array([[2, 3, 4],
       [1, 2, 3],
       [2, 5, 1]])

## dot product
* A key distinction to make with arithmetic is the case of matrix multiplication using the dot product. NumPy gives every matrix a dot() method we can use to carry-out dot product operations with other matrices:

In [29]:
np.dot(a,b)

array([[10, 22, 13],
       [15, 32, 21],
       [15, 27, 32]])

In [30]:
a*b # power

array([[ 2,  6, 12],
       [ 2,  6, 12],
       [ 8, 25,  1]])

In [31]:
s=np.sqrt(xy) #square root

In [32]:
s

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974],
        [2.64575131, 2.82842712, 3.        ]]])

In [33]:
np.max(xy)

9

## Trigonometric Functions

In [35]:
np.sin(xy)

array([[[ 0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ],
        [ 0.6569866 ,  0.98935825,  0.41211849]]])

In [36]:
np.cos(xy)

array([[[ 0.54030231, -0.41614684, -0.9899925 ],
        [-0.65364362,  0.28366219,  0.96017029],
        [ 0.75390225, -0.14550003, -0.91113026]]])

In [37]:
np.tan(xy)

array([[[ 1.55740772, -2.18503986, -0.14254654],
        [ 1.15782128, -3.38051501, -0.29100619],
        [ 0.87144798, -6.79971146, -0.45231566]]])

In [38]:
z = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:' )
print (z) 
print ('\n'  )

print ('After rounding:' )
print (np.around(z) )
print(np.around(z, decimals = 2) )

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.     5.55 123.     0.57  25.53]
